[package]
name = "lh-model-provider"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
thiserror.workspace = true
reqwest.workspace = true
toml.workspace = true
tokio.workspace = true

[dev-dependencies]
wiremock.workspace = true
